# Generated by Django 4.0.4 on 2022-04-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='gamechat.message'),
        ),
    ]
